server:
  port: 8080
spring:
  application:
    name: coin-common
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
      config:
        enabled: false
    sentinel:
      filter:
        enabled: false
      transport:
        port: 8719
        dashboard: sentinel-server:8858
  datasource:
    url: jdbc:mysql://mysql-server:3306/coin-exchange?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    password: pncalbl123
    host: redis-server
    port: 6380

swagger2:
  base-package: com.pncalbl.controller
  name: pncalbl
  url: https://github.com/pncalbl
  email: pncalbl@qq.com
  title: coin-common 模块测试
  description: coin-common 模块测试开发
  version: 2.0
  terms-of-service-url: pnca

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local: # 本地缓存的实现
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote: # 远程缓存的实现
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}
