server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848

  datasource:
    url: jdbc:mysql://mysql-server:3306/coin-exchange?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    password: pncalbl123
#    host: redis-server
#    port: 6380
