server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql-server:3306/coin-exchange?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    password: pncalbl123
    host: redis-server
    port: 6380

  cloud:
    sentinel:
      transport:
        dashboard: sentinel-server:8858
    alicloud:
      access-key: LTAI5tE62iYHxNxJEdWdua9i
      secret-key: qNaJ4XJoNZwSCEWY4QFgUNxC1gBVmf
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mappers/*Mapper.xml

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host}
      port: ${spring.redis.port}
      password: ${spring.redis.password}

swagger2:
  base-package: com.pncalbl.controller
  name: pncalbl
  url: https://github.com/pncalbl/
  email: pncalbl@qq.com
  title: 后台管理系统的 API 接口
  description: 后台管理系统的 API 接口演示
  version: 1.0
  terms-of-service-url: https://github.com/pncalbl/coin-exchange